import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { CartProvider } from "@/lib/cart-store";
import { Suspense } from "react";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "./_context/authContext";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <AuthProvider>
          <Suspense>
            <ThemeProvider enableSystem attribute="class" defaultTheme="system">
              <CartProvider>
                <main>{children}</main>
                <Toaster />
              </CartProvider>
            </ThemeProvider>
          </Suspense>
        </AuthProvider>
      </body>
    </html>
  );
}
